[theme]
primaryColor = "#4c8bf5"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#1E2130"
textColor = "#FAFAFA"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[deprecation]
showPyplotGlobalUse = false

[global]
developmentMode = false